### PR TITLE
parse more fields for pick and magnitude elements

### PR DESCRIPTION
**Pull request by markhamnr**
Again, let me know if you see a better way of doing anything.

I ignored a couple of fields of type "ResourceReference", because they seem to be URIs or IDs of some sort, and I wasn't sure if they'd be useful without knowing what they reference.  Is it worth just storing them as strings?

### CODE REVIEW

**Comment by crotwell** [comment]
I don't understand ResourceReferences either. Keeping as strings seems safest to me as I am not sure all datacenters treat them the same way. Strings are safe and easy.

All this looks good, thanks.

**Comment by markhamnr** [comment]
FWIW, I'm currently working on beefing up parsing origins, and in the process I gleaned some more information by comparing the (XML) schema for QuakeML to the UML diagram.  It seems like anything typed as a "resource reference" is a kind of ID, but not necessarily in the XML DTD sense of ID and IDREF.  Actually, some of them are that kind of ID or IDREF, but others aren't.

I'm thinking I'll go back and add in all of those fields as strings, except where it's superseded by a linkage (like arrival/pickID -> pick/publicID).

**Comment by crotwell** [comment]
Sounds good. Looking more closely, I think it might be good to keep the ID as a string in addition to making the association. So Arrival probably should have a pickId field regardless of whether or not the pick is associated. It don't know if that ID would ever be used for anything else, and makes sense to not throw it away. Thoughts?

**Comment by markhamnr** [comment]
Actually, for anything like arrival->pick where the relationship is required, it probably doesn't matter?  You could always access arrival.pick.publicID to get the equivalent of arrival.pickID.

If there are cases where there might not be a related element, then I'd agree.

**Pull request merged**
